server:
  port: 9001
  
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      lob:
        non_contextual_creation: true
  sql:
    init:
      mode: always
      platform: postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/pallas
    username: pallas
    password: Oktato123
  thymeleaf:
    cache: false
logging:
  level:
    org:
      springframework: ERROR